export const INDUSTRIES = [
  'IT & Software Development',
  'Technology & Electronics',
  'Finance & Banking',
  'Healthcare & Pharmaceuticals',
  'Manufacturing & Industrial',
  'Education & Training',
  'Construction & Real Estate',
  'Retail & E-commerce',
  'Consulting & Professional Services',
  'Marketing & Advertising',
  'Hospitality & Tourism',
  'Automobile',
  'Government & Public Sector',
  'Other'
];

export const JOB_TYPES = ['Full-time', 'Part-time', 'Internship', 'Hybrid', 'Contract'];

export const INDIA_LOCATIONS = [
  // Major Metro Cities
  'Bengaluru (Bangalore)', 'Mumbai', 'Delhi', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata',
  'Ahmedabad', 'Noida', 'Gurugram (Gurgaon)', 'Navi Mumbai', 'Thane',
  // IT & Tech Hubs
  'Whitefield, Bengaluru', 'Electronic City, Bengaluru', 'Koramangala, Bengaluru',
  'Baner, Pune', 'Hinjewadi, Pune', 'Magarpatta, Pune', 'Kharadi, Pune',
  'HITEC City, Hyderabad', 'Gachibowli, Hyderabad', 'Kondapur, Hyderabad',
  'Cyber City, Gurugram', 'DLF Cyber Hub, Gurugram', 'Sector 62, Noida',
  'Andheri, Mumbai', 'BKC (Bandra Kurla Complex), Mumbai', 'Powai, Mumbai', 'Lower Parel, Mumbai',
  'OMR (Old Mahabalipuram Road), Chennai', 'Tidel Park, Chennai',
  'Salt Lake Sector V, Kolkata',
  // Tier 2 Cities
  'Jaipur', 'Lucknow', 'Chandigarh', 'Indore', 'Bhopal', 'Nagpur', 'Coimbatore', 'Kochi',
  'Thiruvananthapuram', 'Mysuru (Mysore)', 'Mangaluru (Mangalore)', 'Hubli-Dharwad',
  'Vijayawada', 'Visakhapatnam (Vizag)', 'Warangal', 'Tirupati',
  'Madurai', 'Salem', 'Tiruchirappalli (Trichy)', 'Vellore',
  'Surat', 'Vadodara (Baroda)', 'Rajkot', 'Gandhinagar',
  'Patna', 'Ranchi', 'Bhubaneswar', 'Guwahati', 'Dehradun', 'Amritsar', 'Ludhiana',
  'Faridabad', 'Ghaziabad', 'Agra', 'Varanasi', 'Meerut',
  // Special Economic Zones & IT Parks
  'Manyata Tech Park, Bengaluru', 'Embassy Tech Village, Bengaluru',
  'GIFT City, Gandhinagar', 'Rajiv Gandhi IT Park, Chandigarh',
  'Technopark, Thiruvananthapuram', 'Infopark, Kochi', 'SmartCity Kochi',
  // Remote / PAN India
  'Remote (Work From Home)', 'PAN India',
];

export const EDUCATION_DEGREES = [
  // School & Pre-University
  '10th Standard / Secondary School (SSLC / CBSE / ICSE)',
  '12th / Higher Secondary / PUC (Science - PCMB / PCMC)',
  '12th / Higher Secondary / PUC (Commerce)',
  '12th / Higher Secondary / PUC (Arts / Humanities)',
  'Vocational Education / ITI Certificate',
  // Polytechnic & Technical Diplomas
  'Polytechnic Diploma in Computer Science & Engineering',
  'Polytechnic Diploma in Information Technology',
  'Polytechnic Diploma in Civil Engineering',
  'Polytechnic Diploma in Mechanical Engineering',
  'Polytechnic Diploma in Electrical & Electronics (EEE)',
  'Polytechnic Diploma in Electronics & Communication (ECE)',
  'Polytechnic Diploma in Automobile Engineering',
  'Diploma in Pharmacy (D.Pharm)',
  'Diploma in Hotel Management & Catering',
  // General & Undergraduate Degrees
  "Bachelor's Degree / Any Graduate",
  'B.E. / B.Tech in Computer Science & Engineering (CSE)',
  'B.E. / B.Tech in Information Technology (IT)',
  'B.E. / B.Tech in Artificial Intelligence & Machine Learning (AI & ML)',
  'B.E. / B.Tech in Data Science',
  'B.E. / B.Tech in Electronics & Communication Engineering (ECE)',
  'B.E. / B.Tech in Electrical & Electronics Engineering (EEE)',
  'B.E. / B.Tech in Mechanical Engineering',
  'B.E. / B.Tech in Civil Engineering',
  'B.E. / B.Tech in Chemical Engineering',
  'B.E. / B.Tech in Biotechnology',
  'B.E. / B.Tech in Aerospace / Aeronautical Engineering',
  'BCA (Bachelor of Computer Applications)',
  'B.Sc in Computer Science',
  'B.Sc in Information Technology',
  'B.Sc in Data Science / Cyber Security',
  'B.Sc in Mathematics / Statistics',
  'B.Sc in Physics / Chemistry',
  'B.Sc in Biotechnology / Microbiology / Biochemistry',
  'B.Sc in Nursing / Allied Health',
  'B.Sc in Agriculture / Horticulture / Forestry',
  'B.Com (General)',
  'B.Com in Accounting & Finance',
  'B.Com in Taxation',
  'B.Com with Computer Applications',
  'BBA (Bachelor of Business Administration)',
  'BBM (Bachelor of Business Management)',
  'B.A. in Economics',
  'B.A. in English / Literature',
  'B.A. in Journalism & Mass Communication',
  'B.A. in Psychology / Sociology / Political Science',
  'B.Des (Bachelor of Design - UI/UX / Product / Graphic)',
  'B.Arch (Bachelor of Architecture)',
  'B.Pharm (Bachelor of Pharmacy)',
  'Pharm.D (Doctor of Pharmacy)',
  'MBBS (Bachelor of Medicine, Bachelor of Surgery)',
  'BDS (Bachelor of Dental Surgery)',
  'BPT (Bachelor of Physiotherapy)',
  'B.Ed (Bachelor of Education)',
  'B.P.Ed (Bachelor of Physical Education)',
  'B.A. LL.B / B.B.A. LL.B / LL.B (Law)',
  'BHM (Bachelor of Hotel Management)',
  // Postgraduate Degrees
  "Master's Degree / Any Post Graduate",
  'M.Tech / M.E. in Computer Science & Engineering',
  'M.Tech / M.E. in Artificial Intelligence / Data Science',
  'M.Tech / M.E. in VLSI Design & Embedded Systems',
  'M.Tech / M.E. in Software Engineering',
  'M.Tech / M.E. in Mechanical / Thermal Engineering',
  'M.Tech / M.E. in Structural Engineering',
  'MCA (Master of Computer Applications)',
  'M.Sc in Computer Science',
  'M.Sc in Information Technology / Cyber Security',
  'M.Sc in Mathematics / Applied Statistics',
  'M.Sc in Physics / Applied Physics',
  'M.Sc in Chemistry / Organic Chemistry',
  'M.Sc in Biotechnology / Life Sciences',
  'MBA in Finance',
  'MBA in Marketing',
  'MBA in Human Resource Management (HR)',
  'MBA in Operations / Supply Chain Management',
  'MBA in Business Analytics / Data Analytics',
  'MBA in Information Technology (IT)',
  'M.Com (Master of Commerce)',
  'M.A. in Economics',
  'M.A. in English / Linguistics',
  'M.A. in Journalism & Mass Communication',
  'M.Des (Master of Design)',
  'M.Pharm (Master of Pharmacy)',
  'MS (Master of Science / Master of Surgery)',
  'MD (Doctor of Medicine)',
  'MDS (Master of Dental Surgery)',
  'MPT (Master of Physiotherapy)',
  'LL.M (Master of Laws)',
  'M.Ed (Master of Education)',
  // Advanced Research & Doctorate
  'M.Phil (Master of Philosophy)',
  'Ph.D in Computer Science & Engineering',
  'Ph.D in Engineering / Technology',
  'Ph.D in Physical / Chemical / Mathematical Sciences',
  'Ph.D in Biological Sciences / Biotechnology',
  'Ph.D in Management Studies / Commerce',
  'Ph.D in Humanities / Social Sciences',
  'Ph.D in Law',
  'Ph.D / Doctorate (Any Stream)',
  'Post-Doctoral Fellowship (PostDoc)'
];

export const REQUIRED_DOCUMENTS_OPTIONS = [
  'Updated Resume / Curriculum Vitae (CV)',
  'Passport Size Photographs (2-4 copies)',
  'Government Photo ID Proof (Aadhaar / PAN / Voter ID / Passport / Driving License)',
  '10th / Secondary School Marksheet & Passing Certificate',
  '12th / Higher Secondary / PUC Marksheet & Certificate',
  'Diploma Certificate & All Semester Marksheets',
  'Undergraduate Degree Certificate / Provisional Degree',
  'Undergraduate All Semester Marksheets / Consolidated Transcript',
  'Postgraduate Degree Certificate / Marksheets',
  'Previous Employer Relieving Letter & Service Certificate',
  'Last 3 Months Salary Slips',
  'Bank Account Statement (Last 3-6 Months)',
  'Previous Employer Appointment Letter / Offer Letter',
  'College ID Card / Bona Fide Certificate (for Students & Interns)',
  'Portfolio / GitHub Repository / Project Work Samples',
  'Technical / Professional Certifications',
  'Recommendation Letter / Reference Contacts',
  'Caste / Category / Income Certificate (if applicable)',
  'Medical Fitness Certificate',
  'Address Proof Document'
];
